project_name: cc-monorepo
version: 5
langs:
  - rust
targets:
  - arch: x86_64
    os: linux
    os_derivative: any
    os_version:
      type: no
  - arch: wasm32
    os: web
    os_derivative: any
    os_version:
      type: no
deploy_toolkit: docker
cache_files:
  - .git
  - Cargo.lock
  - target
variables: []
pipelines:
  - title: common-ops
    desc: Common monorepo operations
    info: cc-services-common-ops@0.1.0
    tags:
      - cargo
      - clippy
      - lint
    default: true
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/doc
        to: docs
    actions:
      - title: Lint `cc-utils` on x86-64
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy --package cc-utils --target x86_64-unknown-linux-gnu
      - title: Lint `cc-utils` on wasm32
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy --package cc-utils --target wasm32-unknown-unknown --no-default-features --features=reqwest
      - title: Lint `cc-ui-kit`
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --package cc-ui-kit --target wasm32-unknown-unknown
      - title: Lint `cc-error-pages`
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --package cc-error-pages --target wasm32-unknown-unknown
      - title: Lint `cc-server-kit`
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: RUSTFLAGS='--cfg reqwest_unstable' cargo clippy --package cc-server-kit --target x86_64-unknown-linux-gnu
      - title: Lint `cc-server-kit-dsl`
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --package skdsl --target x86_64-unknown-linux-gnu
      - title: Lint `cc-static-server`
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --package cc-static-server --target x86_64-unknown-linux-gnu
      - title: Format
        info: cargo-fmt@0.1.0
        tags: []
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
      - title: Test docs
        info: cargo-doc@0.1.0
        tags:
          - cargo
          - doc
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo test --doc
      - title: Generate docs
        info: cargo-doc@0.1.0
        tags:
          - cargo
          - doc
        exec_in_project_dir: false
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo doc --target x86_64-unknown-linux-gnu --workspace --no-deps
  - title: build-static-server
    desc: Build `cc-static-server` and update content storage
    info: cc-services-static-server@0.1.0
    tags:
      - cargo
      - clippy
      - lint
    default: true
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/release/cc-static-server
        to: static-server/cc-static-server
      - from: cc-static-server/static-server.yaml
        to: static-server/static-server.yaml
    actions:
      - title: Sync script to know Rust package version
        info: sync-rust-crate-ver@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: use_from_storage
          content_info: get-know-rust-package-version@latest
      - title: Cargo Build (Release)
        info: cargo-rel@0.1.0
        tags:
          - rust
          - cargo
        requirements:
          - type: exists
            path: /bin/cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo build --release --package cc-static-server --target x86_64-unknown-linux-gnu
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
      - title: UPX Compress
        info: upx-compress@0.1.0
        tags:
          - upx
        requirements:
          - type: exists_any
            paths:
              - /usr/bin/upx
              - ~/.local/bin/upx
        exec_in_project_dir: false
        action:
          type: post_build
          supported_langs:
            - rust
            - go
            - c
            - cpp
          commands:
            - bash_c: upx <af>
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
              daemon: false
              placeholders:
                - <af>
              replacements:
                - group:
                    - from: <af>
                      to:
                        title: target/x86_64-unknown-linux-gnu/release/cc-static-server
                        is_secret: false
                        value:
                          type: plain
                          value: target/x86_64-unknown-linux-gnu/release/cc-static-server
      - title: Auto-upload CC Static Server to Deployer's Storage
        info: auto-upload-static-server@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: add_to_storage
          short_name: static-server
          auto_version_rule:
            type: cmd_stdout
            cmd:
              bash_c: python .depl/rust-crate-ver.py
              ignore_fails: true
              show_success_output: true
              show_bash_c: false
              only_when_fresh: false
          content:
            type: fixed_files
            placements:
              - from: target/x86_64-unknown-linux-gnu/release/cc-static-server
                to: cc-static-server
              - from: cc-static-server/static-server.yaml
                to: static-server.yaml
  - title: build-static-server-debug
    desc: Build `cc-static-server` (debug) and update content storage
    info: cc-services-static-server-debug@0.1.0
    tags:
      - cargo
      - clippy
      - lint
    default: true
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/debug/cc-static-server
        to: static-server/cc-static-server-debug
      - from: cc-static-server/static-server.yaml
        to: static-server/static-server.yaml
    actions:
      - title: Sync script to know Rust package version
        info: sync-rust-crate-ver@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: use_from_storage
          content_info: get-know-rust-package-version@latest
      - title: Cargo Build (Debug)
        info: cargo-debug@0.1.0
        tags:
          - rust
          - cargo
        requirements:
          - type: exists
            path: /bin/cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo build --package cc-static-server --target x86_64-unknown-linux-gnu
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
      - title: Auto-upload CC Static Server to Deployer's Storage
        info: auto-upload-static-server@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: add_to_storage
          short_name: static-server-debug
          auto_version_rule:
            type: cmd_stdout
            cmd:
              bash_c: python .depl/rust-crate-ver.py
              ignore_fails: true
              show_success_output: true
              show_bash_c: false
              only_when_fresh: false
          content:
            type: fixed_files
            placements:
              - from: target/x86_64-unknown-linux-gnu/debug/cc-static-server
                to: cc-static-server
              - from: cc-static-server/static-server.yaml
                to: static-server.yaml
  - title: build-error-pages
    desc: Build `cc-error-pages`
    info: cc-ui-kit-frontend-app-build@0.1.0
    tags:
      - cargo
      - leptos
      - trunk
      - rust
      - wasm
      - web
    default: true
    artifacts:
      - from: cc-error-pages/dist
        to: cc-error-pages/dist
    actions:
      - title: Format `leptos` macroses
        info: leptos-fmt@0.1.0
        tags:
          - rust
          - cargo
          - fmt
        requirements:
          - type: exists
            path: ~/.cargo/bin/leptosfmt
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cd cc-error-pages && leptosfmt -t 2 ./**/*.rs
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
      - title: Format Rust code
        info: cargo-fmt@0.1.0
        tags:
          - rust
          - cargo
          - fmt
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cd cc-error-pages && cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
      - title: Compile Tailwind Styles
        info: tailwind-css@0.1.0
        tags:
          - rust
          - css
          - tailwind
        exec_in_project_dir: false
        action:
          type: pre_build
          supported_langs:
            - css
          commands:
            - bash_c: cd cc-error-pages && tailwindcss -i ./input.css -o ./public/tailwind.css --minify
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
      - title: Trunk Build
        info: trunk-release@0.1.0
        tags:
          - cargo
          - rust
          - trunk
          - wasm
          - web
        requirements:
          - type: exists
            path: ~/.cargo/bin/trunk
        exec_in_project_dir: false
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: >
                RUSTFLAGS="-Zlocation-detail=none -Zfmt-debug=none" 
                CARGO_UNSTABLE_BUILD_STD="std,panic_abort" 
                CARGO_UNSTABLE_BUILD_STD_FEATURES="optimize_for_size,panic_immediate_abort" 
                trunk build --release --config cc-error-pages/Trunk.toml
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
      - title: Optimize WASM
        info: wasm-opt@0.1.0
        tags:
          - wasm
          - wasm-opt
        requirements:
          - type: exists
            path: /bin/wasm-opt
        exec_in_project_dir: false
        action:
          type: post_build
          supported_langs:
            - rust
          commands:
            - bash_c: wasm-opt -Oz --all-features --strip-debug -o {file} {file}
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
              placeholders:
                - "{file}"
              replacements:
                - group:
                    - from: "{file}"
                      to:
                        title: wasm-project-file
                        is_secret: false
                        value:
                          type: plain
                          value: cc-error-pages/dist/cc-error-pages_bg.wasm
      - title: Add `tailwind.css` from `public` to `dist`
        info: add-tailwind-css-to-dist-folder@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: post_build
          supported_langs:
            - rust
          commands:
            - bash_c: cp cc-error-pages/public/tailwind.css cc-error-pages/dist/error_pages_tailwind.css
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
      - title: Add `favicon.ico` from `public` to `dist`
        info: add-favicon-to-dist-folder@0.1.0
        tags: []
        exec_in_project_dir: false
        action:
          type: post_build
          supported_langs:
            - rust
          commands:
            - bash_c: cp cc-error-pages/public/favicon.ico cc-error-pages/dist/
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
  - title: build-skdsl
    desc: Build and install `skdsl`
    info: cc-services-skdsl@0.1.0
    tags:
      - cargo
      - clippy
      - lint
    default: true
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/release/skdsl
        to: skdsl
    actions:
      - title: Lint
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        requirements:
          - type: exists_any
            paths:
              - /bin/cargo
              - ~/.cargo/bin/cargo
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --package skdsl --target x86_64-unknown-linux-gnu
      - title: Format
        info: cargo-fmt@0.1.0
        tags:
          - rust
          - cargo
          - fmt
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cd cc-server-kit-dsl && cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
      - title: Cargo Build (Release)
        info: cargo-rel@0.1.0
        tags:
          - rust
          - cargo
        requirements:
          - type: exists
            path: /bin/cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo build --release --package skdsl --target x86_64-unknown-linux-gnu
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
      - title: UPX Compress
        info: upx-compress@0.1.0
        tags:
          - upx
        requirements:
          - type: exists_any
            paths:
              - /usr/bin/upx
              - ~/.local/bin/upx
        exec_in_project_dir: false
        action:
          type: post_build
          supported_langs:
            - rust
            - go
            - c
            - cpp
          commands:
            - bash_c: upx <af>
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
              daemon: false
              placeholders:
                - <af>
              replacements:
                - group:
                    - from: <af>
                      to:
                        title: target/x86_64-unknown-linux-gnu/release/skdsl
                        is_secret: false
                        value:
                          type: plain
                          value: target/x86_64-unknown-linux-gnu/release/skdsl
      - title: Install to ~/.cargo/bin
        info: install-to-cargo-bin@0.1.1
        tags:
          - cargo
        action:
          type: install
          target:
            arch: x86_64
            os: linux
            os_derivative: any
            os_version:
              type: no
          commands:
            - bash_c: cp -f <af> ~/.cargo/bin
              show_bash_c: false
              placeholders:
                - <af>
              replacements:
                - group:
                    - from: <af>
                      to:
                        title: target/x86_64-unknown-linux-gnu/release/skdsl
                        is_secret: false
                        value:
                          type: plain
                          value: target/x86_64-unknown-linux-gnu/release/skdsl
  - title: debug-skdsl
    desc: Build and install `skdsl`
    info: cc-services-skdsl-debug@0.1.0
    tags:
      - cargo
    default: false
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/debug/skdsl
        to: skdsl-debug
    actions:
      - title: Lint
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        requirements:
          - type: exists_any
            paths:
              - /bin/cargo
              - ~/.cargo/bin/cargo
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --package skdsl --target x86_64-unknown-linux-gnu
      - title: Cargo Build
        info: cargo-build@0.1.0
        tags:
          - rust
          - cargo
        requirements:
          - type: exists
            path: /bin/cargo
        action:
          type: build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo build --package skdsl --target x86_64-unknown-linux-gnu
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
      - title: Install to ~/.cargo/bin
        info: install-to-cargo-bin@0.1.1
        tags:
          - cargo
        action:
          type: install
          target:
            arch: x86_64
            os: linux
            os_derivative: any
            os_version:
              type: no
          commands:
            - bash_c: cp -f <af> ~/.cargo/bin
              show_bash_c: false
              placeholders:
                - <af>
              replacements:
                - group:
                    - from: <af>
                      to:
                        title: target/x86_64-unknown-linux-gnu/debug/skdsl
                        is_secret: false
                        value:
                          type: plain
                          value: target/x86_64-unknown-linux-gnu/debug/skdsl
