project_name: impulse-kit
version: 7
ignore_files:
  - .git
cache_files:
  - Cargo.lock
  - target
variables:
  binary-static-server:
    is_secret: false
    value:
      type: plain
      value: target/x86_64-unknown-linux-gnu/release/iks
  component-accordion:
    is_secret: false
    value:
      type: plain
      value: accordion
  component-alert-dialog:
    is_secret: false
    value:
      type: plain
      value: alert-dialog
  component-alert:
    is_secret: false
    value:
      type: plain
      value: alert
  component-aspect-ratio:
    is_secret: false
    value:
      type: plain
      value: aspect-ratio
  component-avatar:
    is_secret: false
    value:
      type: plain
      value: avatar
  component-badge:
    is_secret: false
    value:
      type: plain
      value: badge
  component-breadcrumb:
    is_secret: false
    value:
      type: plain
      value: breadcrumb
  component-button:
    is_secret: false
    value:
      type: plain
      value: button
  component-dropdown-menu:
    is_secret: false
    value:
      type: plain
      value: dropdown-menu
  component-icon:
    is_secret: false
    value:
      type: plain
      value: icon
  component-input:
    is_secret: false
    value:
      type: plain
      value: input
  component-input-otp:
    is_secret: false
    value:
      type: plain
      value: input-otp
  component-label:
    is_secret: false
    value:
      type: plain
      value: label
  component-popover:
    is_secret: false
    value:
      type: plain
      value: popover
  component-theme:
    is_secret: false
    value:
      type: plain
      value: theme
  empty:
    is_secret: false
    value:
      type: plain
      value: ""
  featureset-utils-wasm32:
    is_secret: false
    value:
      type: plain
      value: " --no-default-features --features=reqwest"
  featureset-all:
    is_secret: false
    value:
      type: plain
      value: " --all-features"
  file-alert-dialog:
    is_secret: false
    value:
      type: plain
      value: alert_dialog
  file-aspect-ratio:
    is_secret: false
    value:
      type: plain
      value: aspect_ratio
  file-dropdown-menu:
    is_secret: false
    value:
      type: plain
      value: dropdown_menu
  file-input-otp:
    is_secret: false
    value:
      type: plain
      value: input_otp
  kit-version:
    is_secret: false
    value:
      type: from_cmd
      cmd: python .depl/rust-crate-ver.py
  package-dsl:
    is_secret: false
    value:
      type: plain
      value: impulse-skdsl
  package-error-pages:
    is_secret: false
    value:
      type: plain
      value: impulse-error-pages
  package-server-kit:
    is_secret: false
    value:
      type: plain
      value: impulse-server-kit
  package-static-server:
    is_secret: false
    value:
      type: plain
      value: impulse-static-server
  package-ui-kit:
    is_secret: false
    value:
      type: plain
      value: impulse-ui-kit
  package-ui-kit-components:
    is_secret: false
    value:
      type: plain
      value: impulse-ui-kit-components
  package-utils:
    is_secret: false
    value:
      type: plain
      value: impulse-utils
  reqwest-unstable-flag:
    is_secret: false
    value:
      type: plain
      value: 'RUSTFLAGS=''--cfg reqwest_unstable'' '
  target-wasm:
    is_secret: false
    value:
      type: plain
      value: wasm32-unknown-unknown
  target-x86:
    is_secret: false
    value:
      type: plain
      value: x86_64-unknown-linux-gnu
actions:
  - info: add-static-server-to-storage@0.1.0
    action:
      type: add_to_storage
      short_name: static-server
      auto_version_rule:
        type: cmd_stdout
        cmd:
          cmd: python .depl/rust-crate-ver.py
          ignore_fails: true
          show_success_output: true
          show_cmd: false
          only_when_fresh: false
      content:
        type: fixed_files
        placements:
          - from: target/x86_64-unknown-linux-gnu/release/iks
            to: iks
          - from: impulse-static-server/static-server.yaml
            to: static-server.yaml
  - info: cargo-fmt@0.1.0
    exec_in_project_dir: true
    action:
      type: staged
      stage: build
      cmd: cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
  - info: cargo-generate-doc@0.1.0
    action:
      type: staged
      stage: build
      cmd: cargo doc --target {target} --workspace --no-deps
      placeholders:
        - "{target}"
  - info: cargo-lint@0.2.0
    action:
      type: staged
      stage: build
      cmd: "{flags}cargo clippy --package {package} --target {target}{features}"
      placeholders:
        - "{flags}"
        - "{package}"
        - "{target}"
        - "{features}"
      show_success_output: true
  - info: cargo-publish@0.2.0
    tags:
      - rust
      - cargo
    requirements:
      - type: exists_any
        paths:
          - /bin/cargo
          - ~/.cargo/bin/cargo
        desc: "Install `cargo` via your package manager or with this command: `curl https://sh.rustup.rs -sSf | sh`."
    action:
      type: staged
      stage: deploy
      cmd: "cargo publish --package {package}{features}"
      placeholders:
        - "{package}"
        - "{features}"
  - info: cargo-release@0.2.0
    tags:
      - rust
      - cargo
    requirements:
      - type: exists_any
        paths:
          - /bin/cargo
          - ~/.cargo/bin/cargo
        desc: "Install `cargo` via your package manager or with this command: `curl https://sh.rustup.rs -sSf | sh`."
    action:
      type: staged
      stage: build
      cmd: "{flags}cargo build --release --package {package} --target {target}{features}"
      placeholders:
        - "{flags}"
        - "{package}"
        - "{target}"
        - "{features}"
  - info: cargo-test-doc@0.1.0
    action:
      type: staged
      stage: build
      cmd: cargo test --doc
  - info: depl-add-component-to-storage@0.1.0
    tags:
      - deployer
    requirements:
      - type: exists_any
        paths:
          - /bin/depl
          - /usr/bin/depl
          - ~/.cargo/bin/depl
          - ~/.local/bin/depl
    action:
      type: staged
      stage: build
      cmd: depl add content -o -c impulse-ui-kit/components/src/{component-file}.rs -p ui-kit-{component-name}@{kit-version}
      placeholders:
        - "{component-name}"
        - "{component-file}"
        - "{kit-version}"
  - info: leptos-fmt@0.1.0
    tags:
      - leptos
      - fmt
    requirements:
      - type: exists
        path: ~/.cargo/bin/leptosfmt
        desc: "Check this: https://github.com/bram209/leptosfmt"
    exec_in_project_dir: true
    action:
      type: staged
      stage: build
      cmd: leptosfmt -t 2 ./**/*.rs
  - info: upx@0.1.0
    requirements:
      - type: exists_any
        paths:
          - /bin/upx
          - /usr/bin/upx
          - ~/.local/bin/upx
    action:
      type: staged
      stage: build
      cmd: upx %af%
      placeholders:
        - "%af%"
  - info: use-rust-package-version@0.1.0
    action:
      type: use_from_storage
      content_info: get-know-rust-package-version@latest
pipelines:
  - title: common-ops
    desc: Common monorepo operations
    info: impulse-kit-common-ops@0.1.0
    tags:
      - cargo
      - clippy
      - lint
      - docs
      - fmt
    default: true
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/doc
        to: docs
    actions:
      - title: Lint `impulse-utils` on x86-64
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": reqwest-unstable-flag
          "{package}": package-utils
          "{target}": target-x86
      - title: Lint `impulse-utils` on wasm32
        used: cargo-lint@0.2.0
        with:
          "{features}": featureset-utils-wasm32
          "{flags}": reqwest-unstable-flag
          "{package}": package-utils
          "{target}": target-wasm
      - title: Lint `impulse-ui-kit`
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": empty
          "{package}": package-ui-kit
          "{target}": target-wasm
      - title: Lint `impulse-error-pages`
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": empty
          "{package}": package-error-pages
          "{target}": target-wasm
      - title: Lint `impulse-server-kit`
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": reqwest-unstable-flag
          "{package}": package-server-kit
          "{target}": target-x86
      - title: Lint `impulse-server-kit-dsl`
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": empty
          "{package}": package-dsl
          "{target}": target-x86
      - title: Lint `impulse-static-server`
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": empty
          "{package}": package-static-server
          "{target}": target-x86
      - title: Format
        used: cargo-fmt@0.1.0
      - title: Test docs
        used: cargo-test-doc@0.1.0
      - title: Generate docs
        used: cargo-generate-doc@0.1.0
        with:
          "{target}": target-x86
  - title: publish
    desc: Publish open-source libraries
    info: impulse-kit-publish@0.1.0
    tags:
      - cargo
      - publish
    default: false
    actions:
      - title: Publish `impulse-utils`
        used: cargo-publish@0.2.0
        with:
          "{features}": featureset-all
          "{package}": package-utils
      - title: Publish `impulse-ui-kit`
        used: cargo-publish@0.2.0
        with:
          "{features}": empty
          "{package}": package-ui-kit
      - title: Publish `impulse-server-kit`
        used: cargo-publish@0.2.0
        with:
          "{features}": empty
          "{package}": package-server-kit
      - title: Publish `impulse-static-server`
        used: cargo-publish@0.2.0
        with:
          "{features}": empty
          "{package}": package-static-server
  - title: export-ui-components
    desc: Export Impulse UI Kit components to Deployer's storage.
    info: impulse-kit-export-ui-kit-components@0.1.0
    tags:
      - deployer
      - components
      - ui-kit
    exclusive_exec_tag: components
    actions:
      - title: Add script to know Impulse Kit version
        used: use-rust-package-version@0.1.0
      - title: Lint components
        used: cargo-lint@0.2.0
        with:
          "{features}": empty
          "{flags}": empty
          "{package}": package-ui-kit-components
          "{target}": target-wasm
      - title: Format `leptos::view!` macro content
        used: leptos-fmt@0.1.0
      - title: Format components before exporting
        used: cargo-fmt@0.1.0
      - title: Add `accordion` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-accordion
          "{component-name}": component-accordion
          "{kit-version}": kit-version
      - title: Add `alert-dialog` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": file-alert-dialog
          "{component-name}": component-alert-dialog
          "{kit-version}": kit-version
      - title: Add `alert` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-alert
          "{component-name}": component-alert
          "{kit-version}": kit-version
      - title: Add `aspect-ratio` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": file-aspect-ratio
          "{component-name}": component-aspect-ratio
          "{kit-version}": kit-version
      - title: Add `avatar` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-avatar
          "{component-name}": component-avatar
          "{kit-version}": kit-version
      - title: Add `badge` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-badge
          "{component-name}": component-badge
          "{kit-version}": kit-version
      - title: Add `breadcrumb` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-breadcrumb
          "{component-name}": component-breadcrumb
          "{kit-version}": kit-version
      - title: Add `button` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-button
          "{component-name}": component-button
          "{kit-version}": kit-version
      - title: Add `dropdown-menu` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": file-dropdown-menu
          "{component-name}": component-dropdown-menu
          "{kit-version}": kit-version
      - title: Add `icon` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-icon
          "{component-name}": component-icon
          "{kit-version}": kit-version
      - title: Add `input` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-input
          "{component-name}": component-input
          "{kit-version}": kit-version
      - title: Add `input-otp` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": file-input-otp
          "{component-name}": component-input-otp
          "{kit-version}": kit-version
      - title: Add `label` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-label
          "{component-name}": component-label
          "{kit-version}": kit-version
      - title: Add `popover` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-popover
          "{component-name}": component-popover
          "{kit-version}": kit-version
      - title: Add `theme` component
        used: depl-add-component-to-storage@0.1.0
        with:
          "{component-file}": component-theme
          "{component-name}": component-theme
          "{kit-version}": kit-version
  - title: build-static-server
    info: impulse-kit-build-static-server@0.1.0
    artifacts:
      - from: target/x86_64-unknown-linux-gnu/release/iks
        to: static-server/iks
      - from: impulse-static-server/static-server.yaml
        to: static-server/static-server.yaml
    actions:
      - title: Sync script to know Rust package version
        used: use-rust-package-version@0.1.0
      - title: Build (release mode)
        used: cargo-release@0.2.0
        with:
          "{features}": empty
          "{flags}": empty
          "{package}": package-static-server
          "{target}": target-x86
      - title: Compress
        used: upx@0.1.0
        with:
          "%af%": binary-static-server
      - title: Auto-upload Static Server to Deployer's Storage
        used: add-static-server-to-storage@0.1.0
