[package]
name = "impulse-static-server"
description = "Simple static server"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[[bin]]
name = "iks"
path = "src/main.rs"

[dependencies]
impulse-server-kit = { workspace = true, features = ["http3", "impulse-ring", "cors", "acme", "oapi", "otel", "force-https", "static-server"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "sync"] }
