[package]
name = "cc-static-server"
description = "Simple static server"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[dependencies]
cc-server-kit = { workspace = true, features = ["http3", "cors", "acme", "oapi", "otel", "force-https"] }
dashmap = { workspace = true }
fs-change-notifier = { workspace = true }
headers = { workspace = true }
mime = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
