//! Build script that exposes the component sources to the Tailwind CSS scanner.
//!
//! The components ship their styling as Tailwind utility classes embedded in the
//! `leptos::view!` macros. Tailwind only emits CSS for classes it can find while
//! scanning source files, but a downstream project that pulls this crate from
//! crates.io / git keeps that source inside the (read-only, version-specific)
//! Cargo registry — a path nobody can hardcode in their `input.css`.
//!
//! To fix this without forcing users to copy the components into their own tree,
//! this script:
//!   1. concatenates every component source file into a single, stable scan file
//!      placed in `OUT_DIR` (`impulse-ui-kit-components-sources.rs`);
//!   2. publishes the absolute path of both that bundle and the crate's `src`
//!      directory as build-script metadata.
//!
//! Because the crate declares `links = "impulse-ui-kit-components"`, the metadata
//! reaches every dependent's build script as environment variables:
//!   * `DEP_IMPULSE_UI_KIT_COMPONENTS_STYLES`     — the aggregated scan file;
//!   * `DEP_IMPULSE_UI_KIT_COMPONENTS_SOURCE_DIR` — the crate `src` directory.
//!
//! A consumer's `build.rs` can then write a tiny `@source "...";` partial that
//! their `style.css` imports, so their own Tailwind pass compiles the component
//! classes together with their own classes, theme and `tw-animate.css`. See the
//! `examples/showcase` crate for a complete, working setup.

use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by Cargo");
  let out_dir = env::var("OUT_DIR").expect("OUT_DIR is always set by Cargo");

  let src_dir = Path::new(&manifest_dir).join("src");

  // Collect every Rust source file so a single `@source` can cover the whole
  // component library.
  let mut sources = Vec::new();
  collect_rs(&src_dir, &mut sources);
  sources.sort();

  let mut bundle = String::from("// Generated by impulse-ui-kit-components/build.rs — do not edit.\n");
  for path in &sources {
    if let Ok(content) = fs::read_to_string(path) {
      bundle.push_str(&content);
      bundle.push('\n');
    }
    println!("cargo::rerun-if-changed={}", path.display());
  }

  // Keep the `.rs` extension: Tailwind skips `.css` files when looking for class
  // candidates, but scans Rust sources just like the originals.
  let bundle_path = Path::new(&out_dir).join("impulse-ui-kit-components-sources.rs");
  fs::write(&bundle_path, bundle).expect("failed to write the aggregated Tailwind scan file");

  // Hand both the aggregated file and the raw source directory to dependents.
  println!("cargo::metadata=styles={}", bundle_path.display());
  println!("cargo::metadata=source_dir={}", src_dir.display());

  println!("cargo::rerun-if-changed={}", src_dir.display());
  println!("cargo::rerun-if-changed=build.rs");
}

/// Recursively gather all `.rs` files under `dir`.
fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
  let Ok(entries) = fs::read_dir(dir) else {
    return;
  };
  for entry in entries.flatten() {
    let path = entry.path();
    if path.is_dir() {
      collect_rs(&path, out);
    } else if path.extension() == Some(OsStr::new("rs")) {
      out.push(path);
    }
  }
}
