[package]
name = "impulse-error-pages"
description = "Error pages for standard Server Kit errors"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[dependencies]
icondata = { workspace = true, features = ["lucide"] }
impulse-utils = { workspace = true, features = ["reqwest"] }
impulse-ui-kit = { workspace = true }
impulse-ui-kit-components = { workspace = true }
leptos = { workspace = true, features = ["csr"] }
leptos_meta = { workspace = true }
web-sys = { workspace = true, features = ["Document", "Location"] }

[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "ru"]
locales-dir = "./locales"
