//! Wires the `impulse-ui-kit-components` Tailwind sources into this example's
//! stylesheet without copying any component code.
//!
//! `impulse-ui-kit-components`' build script publishes the absolute path of an
//! aggregated scan file as `DEP_IMPULSE_UI_KIT_COMPONENTS_STYLES`. Here we drop
//! a one-line `@source "...";` partial next to `input.css`, which `input.css`
//! imports. The project's single Tailwind pass then emits CSS for the component
//! classes alongside this example's own classes, the theme and `tw-animate.css`.
//!
//! This is exactly the setup a downstream project would use — see the crate
//! README — the only difference being that here the dependency happens to live
//! in the same workspace.

use std::path::Path;
use std::{env, fs};

const GENERATED: &str = ".tailwind-sources.css";

fn main() {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by Cargo");
  let partial = Path::new(&manifest_dir).join(GENERATED);

  // Prefer the aggregated scan file; fall back to the raw source directory.
  let source = env::var("DEP_IMPULSE_UI_KIT_COMPONENTS_STYLES")
    .or_else(|_| env::var("DEP_IMPULSE_UI_KIT_COMPONENTS_SOURCE_DIR"));

  let contents = match source {
    Ok(path) => format!(
      "/* Generated by build.rs — do not edit. Picks up Tailwind classes from impulse-ui-kit-components. */\n@source \"{path}\";\n"
    ),
    // Keep the import valid even if the metadata is unavailable for some reason.
    Err(_) => "/* impulse-ui-kit-components styles path was not provided by its build script */\n".to_string(),
  };

  fs::write(&partial, contents).expect("failed to write the generated Tailwind sources partial");

  println!("cargo::rerun-if-changed=build.rs");
}
