[package]
name = "impulse-utils"
description = "Bunch of fullstack utils"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[features]
default = ["salvo", "reqwest", "mresult", "cresult"]
salvo = ["dep:salvo"]
reqwest = ["dep:reqwest", "cresult"]
mresult = ["salvo"]
cresult = []

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"], optional = true }
rmp-serde = { workspace = true }
serde = { version = "1", features = ["derive"] }
tracing = { workspace = true }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
salvo = { workspace = true, features = ["oapi", "rustls", "compression", "aws-lc-rs"], optional = true }
sonic-rs = { workspace = true }
