[package]
name = "impulse-ui-kit"
description = "Powerful frontend framework based on Leptos"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[features]
default = ["csr"]
csr = [
  "leptos/csr",
  "dep:console_error_panic_hook",
  "dep:console_log",
  "dep:web-sys",
  "dep:leptos-use",
  "leptos-use/use_color_mode",
  "web-sys/Window",
  "web-sys/Storage",
  "web-sys/Navigator",
  "web-sys/KeyboardEvent",
]
hydrate = [
  "leptos/hydrate",
  "dep:console_error_panic_hook",
  "dep:console_log",
  "dep:web-sys",
  "dep:leptos-use",
  "leptos-use/use_color_mode",
  "web-sys/Window",
  "web-sys/Storage",
  "web-sys/Navigator",
  "web-sys/KeyboardEvent",
]
ssr = [
  "leptos/ssr",
  "dep:leptos_meta",
]
websocket = [
  "dep:js-sys",
  "dep:wasm-bindgen",
  "dep:web-sys",
  "web-sys/BinaryType",
  "web-sys/CloseEvent",
  "web-sys/MessageEvent",
  "web-sys/WebSocket",
]
webtransport = [
  "dep:js-sys",
  "dep:wasm-bindgen",
  "dep:wasm-bindgen-futures",
  "dep:web-sys",
  "web-sys/Window",
  "web-sys/ReadableStream",
  "web-sys/ReadableStreamDefaultReader",
  "web-sys/WebTransport",
  "web-sys/WebTransportBidirectionalStream",
  "web-sys/WebTransportCloseInfo",
  "web-sys/WebTransportDatagramDuplexStream",
  "web-sys/WebTransportOptions",
  "web-sys/WebTransportReceiveStream",
  "web-sys/WebTransportSendStream",
  "web-sys/WritableStream",
  "web-sys/WritableStreamDefaultWriter",
]

[dependencies]
console_error_panic_hook = { workspace = true, optional = true }
console_log = { workspace = true, optional = true }
impulse-utils = { workspace = true, features = ["cresult"] }
js-sys = { workspace = true, optional = true }
leptos = { workspace = true }
leptos-use = { workspace = true, optional = true }
leptos_meta = { workspace = true, optional = true }
log = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
