//! Build-script helpers for wiring Rust UI component sources into a Tailwind CSS build.
//!
//! Tailwind only emits CSS for classes it can find while scanning source files.
//! Components written in Rust embed their classes in `leptos::view!` macros, so
//! the consuming project's Tailwind pass must scan the component crates' sources
//! — which, for a dependency pulled from crates.io / git, live in the read-only
//! Cargo registry under a path nobody can hardcode in their `input.css`.
//!
//! These helpers bridge that gap using Cargo's `links` / `DEP_*` build metadata,
//! so component libraries can be consumed as plain Cargo dependencies instead of
//! being copied into every project. There are two roles:
//!
//! * a **component library** calls [`export`] from its `build.rs` to publish the
//!   absolute path of an aggregated scan file — its own sources, plus any
//!   upstream libraries it builds on top of — as `DEP_<LINKS>_STYLES`;
//! * a **consumer** (an app or example) calls [`write_source_partial`] to turn
//!   those published paths into a `@source "...";` partial that its `style.css`
//!   imports next to `tailwindcss` and friends.
//!
//! Because [`export`] folds upstream bundles into its own, the pattern composes
//! to any depth: each level only ever reads the `DEP_*_STYLES` of its *direct*
//! dependencies.

use std::ffi::OsStr;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

/// Aggregate this crate's component sources — and any forwarded upstream bundles
/// — into a single scan file, and publish its path to direct dependents.
///
/// Call this from a component library's `build.rs`. The crate must declare a
/// `links` key in its `Cargo.toml` for the metadata to reach dependents; Cargo
/// then exposes it to their build scripts as:
///
/// * `DEP_<LINKS>_STYLES` — the aggregated scan file (pass this onward), and
/// * `DEP_<LINKS>_SOURCE_DIR` — this crate's raw `src` directory.
///
/// `upstream` lists the `DEP_*_STYLES` environment variables of the component
/// libraries this crate builds on top of. Their contents are folded into the
/// published bundle, so downstream consumers only ever deal with a single path.
/// Missing variables are skipped.
///
/// ```no_run
/// // build.rs of a library built on top of impulse-ui-kit-components:
/// fn main() {
///   impulse_tailwind_sources::export(&["DEP_IMPULSE_UI_KIT_COMPONENTS_STYLES"]);
/// }
/// ```
pub fn export(upstream: &[&str]) {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo");
  let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo");
  let pkg = env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME is set by Cargo");

  let src_dir = Path::new(&manifest_dir).join("src");

  // Collect every Rust source so a single `@source` can cover the whole crate.
  let mut sources = Vec::new();
  collect_rs(&src_dir, &mut sources);
  sources.sort();

  let mut bundle = format!("// Generated by impulse-tailwind-sources for `{pkg}` — do not edit.\n");
  for path in &sources {
    if let Ok(content) = fs::read_to_string(path) {
      bundle.push_str(&content);
      bundle.push('\n');
    }
    println!("cargo::rerun-if-changed={}", path.display());
  }

  // Fold in upstream libraries so the published bundle is self-contained.
  for var in upstream {
    if let Ok(path) = env::var(var) {
      if let Ok(content) = fs::read_to_string(&path) {
        bundle.push_str(&content);
        bundle.push('\n');
      }
      println!("cargo::rerun-if-changed={path}");
    }
  }

  // Keep the `.rs` extension: Tailwind skips `.css` files when scanning for
  // class candidates, but reads Rust sources just like the originals.
  let bundle_path = Path::new(&out_dir).join(format!("{pkg}-tailwind-sources.rs"));
  fs::write(&bundle_path, bundle).expect("failed to write the aggregated Tailwind scan file");

  println!("cargo::metadata=styles={}", bundle_path.display());
  println!("cargo::metadata=source_dir={}", src_dir.display());
  println!("cargo::rerun-if-changed={}", src_dir.display());
  println!("cargo::rerun-if-changed=build.rs");
}

/// Write a `@source "...";` partial pointing at every available styles bundle in
/// `upstream`, for a consumer's `style.css` to `@import`.
///
/// Call this from an app's or example's `build.rs`. Each entry of `upstream` is
/// a `DEP_*_STYLES` (or `DEP_*_SOURCE_DIR`) environment variable published by a
/// component library's [`export`]. Missing variables are skipped, so the call
/// stays correct even if a component dependency is optional.
///
/// ```no_run
/// // build.rs of an app/example consuming impulse-ui-kit-components:
/// fn main() {
///   let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
///   let partial = std::path::Path::new(&manifest_dir).join(".tailwind-sources.css");
///   impulse_tailwind_sources::write_source_partial(partial, &["DEP_IMPULSE_UI_KIT_COMPONENTS_STYLES"]);
/// }
/// ```
pub fn write_source_partial(partial: impl AsRef<Path>, upstream: &[&str]) {
  let mut out = String::from("/* Generated by impulse-tailwind-sources — do not edit. */\n");

  let mut any = false;
  for var in upstream {
    if let Ok(path) = env::var(var) {
      // `unwrap` on a String write is infallible.
      let _ = writeln!(out, "@source \"{path}\";");
      any = true;
      println!("cargo::rerun-if-changed={path}");
    }
  }
  if !any {
    out.push_str("/* no DEP_*_STYLES metadata was provided by dependencies */\n");
  }

  fs::write(partial.as_ref(), out).expect("failed to write the Tailwind @source partial");
  println!("cargo::rerun-if-changed=build.rs");
}

/// Recursively gather all `.rs` files under `dir`.
fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
  let Ok(entries) = fs::read_dir(dir) else {
    return;
  };
  for entry in entries.flatten() {
    let path = entry.path();
    if path.is_dir() {
      collect_rs(&path, out);
    } else if path.extension() == Some(OsStr::new("rs")) {
      out.push(path);
    }
  }
}
